export type MenuCategory =
  "Coffee" | "Tea" | "Breakfast" | "Desserts" | "Bakery" | "Cold Drinks" | "Specials";

export interface MenuItem {
  id: string;
  name: string;
  description: string;
  price: number;
  calories: number;
  category: MenuCategory;
  veg: boolean;
  popular?: boolean;
  available?: boolean;
  image: string;
}

const img = (q: string) => `https://images.unsplash.com/${q}?auto=format&fit=crop&w=1000&q=70`;

export const menu: MenuItem[] = [
  {
    id: "m1",
    name: "Signature Espresso",
    description: "Single-origin Ethiopian, honeyed and floral with a lingering caramel finish.",
    price: 4.5,
    calories: 5,
    category: "Coffee",
    veg: true,
    popular: true,
    available: true,
    image: img("photo-1510707577719-ae7c14805e3a"),
  },
  {
    id: "m2",
    name: "Vanilla Bean Latte",
    description: "Slow-steamed milk, Madagascar vanilla, double ristretto shot.",
    price: 6.0,
    calories: 180,
    category: "Coffee",
    veg: true,
    popular: true,
    available: true,
    image: img("photo-1541167760496-1628856ab772"),
  },
  {
    id: "m3",
    name: "Iced Nitro Cold Brew",
    description: "Twelve-hour steeped, nitrogen-infused, velvet mouthfeel.",
    price: 6.5,
    calories: 15,
    category: "Cold Drinks",
    veg: true,
    available: true,
    image: img("photo-1461023058943-07fcbe16d735"),
  },
  {
    id: "m4",
    name: "Cortado",
    description: "Equal parts espresso and warm silky milk. Balanced, quiet, precise.",
    price: 5.0,
    calories: 90,
    category: "Coffee",
    veg: true,
    available: true,
    image: img("photo-1497935586351-b67a49e012bf"),
  },
  {
    id: "m5",
    name: "Matcha Ceremonial",
    description: "First-harvest Uji matcha whisked to a jade cloud.",
    price: 6.5,
    calories: 110,
    category: "Tea",
    veg: true,
    popular: true,
    available: true,
    image: img("photo-1536256263959-770b48d82b0a"),
  },
  {
    id: "m6",
    name: "Rose Earl Grey",
    description: "Ceylon black tea, bergamot, Persian rose petals.",
    price: 5.5,
    calories: 5,
    category: "Tea",
    veg: true,
    available: true,
    image: img("photo-1571934811356-5cc061b6821f"),
  },
  {
    id: "m7",
    name: "Truffle Mushroom Toast",
    description: "Sourdough, wild mushrooms, black truffle, poached farm egg.",
    price: 14.0,
    calories: 420,
    category: "Breakfast",
    veg: true,
    popular: true,
    available: true,
    image: img("photo-1525351484163-7529414344d8"),
  },
  {
    id: "m8",
    name: "Smoked Salmon Bagel",
    description: "House-cured salmon, whipped dill cream cheese, capers, red onion.",
    price: 15.5,
    calories: 510,
    category: "Breakfast",
    veg: false,
    available: true,
    image: img("photo-1592417817098-8fd3d9eb14a5"),
  },
  {
    id: "m9",
    name: "Belgian Waffles",
    description: "Pearl-sugar Liège waffles, seasonal berries, whipped mascarpone.",
    price: 12.0,
    calories: 480,
    category: "Breakfast",
    veg: true,
    available: true,
    image: img("photo-1562376552-0d160a2f238d"),
  },
  {
    id: "m10",
    name: "Pistachio Tiramisu",
    description: "Espresso-soaked ladyfingers, pistachio mascarpone, cocoa dust.",
    price: 9.5,
    calories: 380,
    category: "Desserts",
    veg: true,
    popular: true,
    available: true,
    image: img("photo-1571877227200-a0d98ea607e9"),
  },
  {
    id: "m11",
    name: "Dark Chocolate Torte",
    description: "70% Valrhona, salted caramel, hazelnut praline.",
    price: 10.0,
    calories: 460,
    category: "Desserts",
    veg: true,
    available: true,
    image: img("photo-1578985545062-69928b1d9587"),
  },
  {
    id: "m12",
    name: "Butter Croissant",
    description: "Laminated 27 layers. Baked at dawn. Best warm.",
    price: 4.5,
    calories: 260,
    category: "Bakery",
    veg: true,
    popular: true,
    available: true,
    image: img("photo-1555507036-ab1f4038808a"),
  },
  {
    id: "m13",
    name: "Almond Danish",
    description: "Flaky pastry, frangipane, toasted almonds, apricot glaze.",
    price: 5.0,
    calories: 340,
    category: "Bakery",
    veg: true,
    available: true,
    image: img("photo-1509365465985-25d11c17e812"),
  },
  {
    id: "m14",
    name: "Iced Rose Lemonade",
    description: "House rose syrup, pressed lemons, sparkling water.",
    price: 6.0,
    calories: 90,
    category: "Cold Drinks",
    veg: true,
    available: true,
    image: img("photo-1621263764928-df1444c5e859"),
  },
  {
    id: "m15",
    name: "Affogato al Tartufo",
    description: "Vanilla bean gelato drowned in espresso, drizzled with truffle honey.",
    price: 8.5,
    calories: 320,
    category: "Specials",
    veg: true,
    popular: true,
    available: true,
    image: img("photo-1497515114629-f71d768fd07c"),
  },
  {
    id: "m16",
    name: "Saffron Cardamom Latte",
    description: "Kashmir saffron, green cardamom, house-roasted espresso.",
    price: 7.0,
    calories: 210,
    category: "Specials",
    veg: true,
    available: true,
    image: img("photo-1572442388796-11668a67e53d"),
  },
];

export const categories: (MenuCategory | "All")[] = [
  "All",
  "Coffee",
  "Tea",
  "Breakfast",
  "Desserts",
  "Bakery",
  "Cold Drinks",
  "Specials",
];
